### ISSUE TITLE
Match current favicon standards

### ISSUE THREAD

**Issue by Newnab** [EtchUK/Etch.OrchardCore.Favicon#1]
Currently our options are:

Favicon (ico, 192x192)
Apple Touch Icon (png, 192x192)
Tile (png, 558x558)
TileWide (png, 558x270)
Browser Config (xml)
Web App Manifest (json)

Given we use Realfavicongenerator to produce favicons to the currently coalesced community standards (as discussed on https://realfavicongenerator.net/faq). Given what the generator currently outputs by default I believe these options should actually currently be:

Favicon Fallback (ico, 32x32)
Default Favicon (png, 16x16)
Large Favicon (png, 32x32)
Apple Touch Icon (png, 180x180)
Android Small Icon (png, 192x192)
Android Large Icon (png, 512x512)
MS Tile (png, 150x150)
Browser Config (xml) - Unchanged from current
Site Web Manifest (.webmanifest)
Safari Pinned Tab (svg)

They're no longer providing wide MS tiles by default so I'm guessing the usage is so low that they're not worthwhile. If we did want to keep wide tiles then the proper size would be 310x150.

Additionally, the code output should look like this (in particular note that the ico file should not be specified, it's what the browser looks for by default if it doesn't allow any of these better formats)
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

We should probably provide CMS properties for picking the safari pinned tab colour, tile colour and theme colour.

**Comment by peterkeating** [comment]
@Newnab Got all the functionality in place I believe. Need to go through and update the docs - https://github.com/EtchUK/Etch.OrchardCore.Favicon#enabling-feature
