### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by 4m-world** [EtchUK/Etch.OrchardCore.Favicon#6]
Do you have a working example for this module, I tried to use in a custom theme but it did not show load any of the resources.

Thank you for your great work

**Comment by peterkeating** [comment]
@4m-world How do you mean an example? If you add this module as a reference to your project, then enable the "Favicons" feature, you should then see a "Favicon" option within the admin menu. From there you can upload/select an image from the media library that will represent the favicon for the site. Additionally you can define other icons (e.g. apple touch).

See usage instructions in the README - https://github.com/EtchUK/Etch.OrchardCore.Favicon#usage

**Comment by 4m-world** [comment]
@peterkeating thank you for your response, I had a problem with where none of the assets loaded, which was due to two factors:
- different OrchardCore version
- I did notice meta tag that been already at the top of head tag, which hid the ones inserted by the filter.
